name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          echo "$KEY" > identity.pem
          chmod 400 identity.pem
          flyctl deploy --remote-only
          EOF
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          KEY: ${{ secrets.KEY }}